num_tokens: 8192 
vae: dvae
vae_path: /datasets/vae.pt
web_dataset: True
use_tpus: True
backup: True
num_workers: 0
train_dir: 'gs://lgai-vision-img-txt-wds-eu/imgtxt-train/train{000000..000662}.tar'
val_dir: 'gs://lgai-vision-img-txt-wds-eu/imgtxt-valid/ds.tar'
dataset_size: [5169754, 636731]
