num_tokens: 8192 
model: gvqvae 
ch_mult: [1,1,2,4]
attn_resolutions: [32] 
web_dataset: True
use_tpus: True
backup: True
log_images: True
num_workers: 0
train_dir: 'gs://lgai-vision-wds-img-only-wds-eu/img_train.tar'
val_dir: 'gs://lgai-vision-wds-img-only-wds-eu/img_valid.tar'
dataset_size: [8196535, 624508]



